### ISSUE TITLE
Want to collaborate

### ISSUE THREAD

**Issue by danimydev** [adrian44s/TypingTest#1]
Hey wasup folks👋!

Would me nice to create a new branch and rebuild this using a framework to make it more scalable so it is easier adding new features!
Here are some suggestions:
- [React](https://www.google.com/search?q=react&rlz=1C1VDKB_esCO1034CO1034&oq=react&aqs=chrome..69i57j69i59l2j0i512j69i60l4.880j0j7&sourceid=chrome&ie=UTF-8)
- [Fresh](https://fresh.deno.dev/)
- [Vue](https://vuejs.org/)

![NyanCatGIF](https://github.com/adrian44s/TypingTest/assets/31113489/10f5c4fa-5ffa-42d2-9945-9ed20376221a)

**Comment by adrian44s** [comment]
hello, we are aware that we need to update the site with some framework would be the best way to improve the site but my partner needs to learn how to use them first for a good execution and since it is a joint work I need to give him time to learn and develop in react, which is the framework we agreed to use for the site.
